//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Finance.ConsoleApp.FinanceService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FinanceService.IVatCodes")]
    public interface IVatCodes {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVatCodes/GetVatCodes", ReplyAction="http://tempuri.org/IVatCodes/GetVatCodesResponse")]
        Finance.ConsoleApp.FinanceService.GetVatCodesResponse GetVatCodes(Finance.ConsoleApp.FinanceService.GetVatCodesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVatCodes/UpdateVatCodes", ReplyAction="http://tempuri.org/IVatCodes/UpdateVatCodesResponse")]
        Finance.ConsoleApp.FinanceService.UpdateVatCodesResponse UpdateVatCodes(Finance.ConsoleApp.FinanceService.UpdateVatCodesRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetVatCodes", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetVatCodesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Finance.Shared.Common.OperationRequest<Finance.Shared.Models.Shared.GetFilter> request;
        
        public GetVatCodesRequest() {
        }
        
        public GetVatCodesRequest(Finance.Shared.Common.OperationRequest<Finance.Shared.Models.Shared.GetFilter> request) {
            this.request = request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetVatCodesResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetVatCodesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Finance.Shared.Common.OperationResponse<Finance.Shared.Models.Codes.VATCodes.VatCodeModel[]> GetVatCodesResult;
        
        public GetVatCodesResponse() {
        }
        
        public GetVatCodesResponse(Finance.Shared.Common.OperationResponse<Finance.Shared.Models.Codes.VATCodes.VatCodeModel[]> GetVatCodesResult) {
            this.GetVatCodesResult = GetVatCodesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateVatCodes", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UpdateVatCodesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Finance.Shared.Common.OperationRequest<Finance.Shared.Models.Codes.VATCodes.VatCodeEditModel[]> request;
        
        public UpdateVatCodesRequest() {
        }
        
        public UpdateVatCodesRequest(Finance.Shared.Common.OperationRequest<Finance.Shared.Models.Codes.VATCodes.VatCodeEditModel[]> request) {
            this.request = request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateVatCodesResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UpdateVatCodesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Finance.Shared.Common.OperationResponse<Finance.Shared.Common.Null> UpdateVatCodesResult;
        
        public UpdateVatCodesResponse() {
        }
        
        public UpdateVatCodesResponse(Finance.Shared.Common.OperationResponse<Finance.Shared.Common.Null> UpdateVatCodesResult) {
            this.UpdateVatCodesResult = UpdateVatCodesResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IVatCodesChannel : Finance.ConsoleApp.FinanceService.IVatCodes, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VatCodesClient : System.ServiceModel.ClientBase<Finance.ConsoleApp.FinanceService.IVatCodes>, Finance.ConsoleApp.FinanceService.IVatCodes {
        
        public VatCodesClient() {
        }
        
        public VatCodesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public VatCodesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VatCodesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VatCodesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Finance.ConsoleApp.FinanceService.GetVatCodesResponse GetVatCodes(Finance.ConsoleApp.FinanceService.GetVatCodesRequest request) {
            return base.Channel.GetVatCodes(request);
        }
        
        public Finance.ConsoleApp.FinanceService.UpdateVatCodesResponse UpdateVatCodes(Finance.ConsoleApp.FinanceService.UpdateVatCodesRequest request) {
            return base.Channel.UpdateVatCodes(request);
        }
    }
}
